# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180903_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='latest_transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
                ('fee', models.BigIntegerField()),
                ('height', models.BigIntegerField()),
                ('senderid', models.CharField(max_length=50)),
                ('recipientid', models.CharField(max_length=50)),
                ('timestamp', models.BigIntegerField()),
                ('txtype', models.BigIntegerField()),
                ('confirmations', models.BigIntegerField()),
            ],
        ),
    ]
