# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_latest_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='last_blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generator', models.CharField(max_length=50)),
                ('height', models.BigIntegerField()),
                ('blockid', models.CharField(max_length=50)),
                ('reward', models.BigIntegerField()),
                ('timestamp', models.CharField(max_length=50)),
                ('totalamount', models.CharField(max_length=50)),
                ('totalfee', models.BigIntegerField()),
                ('totalforged', models.BigIntegerField()),
                ('transactionscount', models.BigIntegerField()),
                ('username', models.CharField(max_length=50)),
                ('rank', models.BigIntegerField()),
            ],
        ),
    ]
